name: kindling
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - decorator=5.1.0
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2021.4.0
  - ipython=7.29.0
  - jedi=0.18.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1l
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - python=3.8.12
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - traitlets=5.1.1
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - backports-entry-points-selectable==1.1.1
    - black==21.10b0
    - cerberus==1.3.2
    - cfgv==3.3.1
    - charset-normalizer==2.0.7
    - click==8.0.3
    - cycler==0.11.0
    - cytoolz==0.11.0
    - distlib==0.3.3
    - filelock==3.4.0
    - flake8==4.0.1
    - fonttools==4.28.1
    - funcy==1.15
    - gin-config==0.3.0
    - identify==2.3.6
    - idna==3.3
    - isort==5.10.1
    - kiwisolver==1.3.2
    - matplotlib==3.5.0
    - mccabe==0.6.1
    - munch==2.5.0
    - mypy-extensions==0.4.3
    - nodeenv==1.6.0
    - packaging==21.2
    - pathspec==0.9.0
    - platformdirs==2.4.0
    - pre-commit==2.15.0
    - protobuf==3.19.1
    - pycodestyle==2.8.0
    - pyflakes==2.4.0
    - pyparsing==2.4.7
    - pyyaml==5.4
    - quinine==0.3.0
    - regex==2021.11.10
    - requests==2.26.0
    - setuptools-scm==6.3.2
    - toml==0.10.2
    - tomli==1.2.2
    - toolz==0.11.2
    - toposort==1.5
    - urllib3==1.26.7
    - virtualenv==20.10.0
