name: kindling
channels:
- defaults
dependencies:
- ca-certificates=2021.10.26
- certifi=2021.10.8
- libcxx=12.0.0
- libedit=3.1.20210910
- libffi=3.2.1
- ncurses=6.3
- openssl=1.1.1l
- pip=21.2.4
- python=3.8.0
- readline=7.0
- setuptools=58.0.4
- sqlite=3.33.0
- tk=8.6.11
- wheel=0.37.0
- xz=5.2.5
- zlib=1.2.11
- pip:
  - backports-entry-points-selectable==1.1.1
  - black==21.10b0
  - cerberus==1.3.2
  - cfgv==3.3.1
  - charset-normalizer==2.0.7
  - click==8.0.3
  - configparser==5.1.0
  - cycler==0.11.0
  - cytoolz==0.11.0
  - distlib==0.3.3
  - docker-pycreds==0.4.0
  - filelock==3.4.0
  - flake8==4.0.1
  - fonttools==4.28.1
  - funcy==1.15
  - gin-config==0.3.0
  - gitdb==4.0.9
  - gitpython==3.1.24
  - identify==2.3.6
  - idna==3.3
  - isort==5.10.1
  - kiwisolver==1.3.2
  - matplotlib==3.5.0
  - mccabe==0.6.1
  - munch==2.5.0
  - mypy-extensions==0.4.3
  - nodeenv==1.6.0
  - numpy==1.21.4
  - packaging==21.2
  - pathspec==0.9.0
  - pathtools==0.1.2
  - pillow==8.4.0
  - platformdirs==2.4.0
  - pre-commit==2.15.0
  - promise==2.3
  - protobuf==3.19.1
  - psutil==5.8.0
  - pycodestyle==2.8.0
  - pyflakes==2.4.0
  - pyparsing==2.4.7
  - python-dateutil==2.8.2
  - pyyaml==5.4
  - quinine==0.3.0
  - regex==2021.11.10
  - requests==2.26.0
  - sentry-sdk==1.4.3
  - setuptools-scm==6.3.2
  - shortuuid==1.0.8
  - six==1.16.0
  - smmap==5.0.0
  - subprocess32==3.5.4
  - termcolor==1.1.0
  - toml==0.10.2
  - tomli==1.2.2
  - toolz==0.11.2
  - toposort==1.5
  - typing-extensions==4.0.0
  - urllib3==1.26.7
  - virtualenv==20.10.0
  - wandb==0.12.6
  - yaspin==2.1.0
